const users = [
	{
		username: "kparkisson0",
		firstName: "Kariotta",
		lastName: "Parkisson",
		password: "$2a$10$B2jQCr.gfll10mow7FwD7uN4ROoG7AIFwe.Gow0thLFJ2X6lAF2k2",
		email: "kparkisson0@smugmug.com",
		location: "Longquan",
		bio: "",
	},
	{
		username: "jyanin1",
		firstName: "Justino",
		lastName: "Yanin",
		password: "$2a$10$61YRpXj9Z8bpR3uHjpbnIuswZfaLV7k6Tr2ZtoE40H7IbFhplI4Hy",
		email: "jyanin1@dagondesign.com",
		location: "Rozmital pod Tremsinem",
		bio: "Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.",
	},
	{
		username: "gbanstead2",
		firstName: "Gery",
		lastName: "Banstead",
		password: "$2a$10$gLcegqq/44nG1ZYs5x7V1OoOgOYyQ/dE4LJgN4k1OMpGJbdyTTPGa",
		email: "gbanstead2@mlb.com",
		location: "Novoukrayinka",
		bio: "",
	},
	{
		username: "jmitchell3",
		firstName: "Jackquelin",
		lastName: "Mitchell",
		password: "$2a$10$0gfqZnV3eOFcsdG9mjJ6ye7T5QJojFzGnLR3sAy/Kr2bgmlVxWjPS",
		email: "jmitchell3@rakuten.co.jp",
		location: "Cimanggu, Fusce consequat, Nulla nisl. Nunc nisl.",
		bio: "",
	},
	{
		username: "ajacobbe4",
		firstName: "Aldus",
		lastName: "Jacobbe",
		password: "$2a$10$yFnbjqlXXOTNN55O3GjmN/Vo/4LDbj7/2s5FXrT3veOqBD92/1Ewq",
		email: "ajacobbe4@nydailynews.com",
		location: "Belisario Dominguez",
		bio: "",
	},
	{
		username: "ereiglar5",
		firstName: "Elyssa",
		lastName: "Reiglar",
		password: "$2a$10$ItRtqX6fDlypg4ba3pwBoWpgt5zjvnWxaYmnzOtdN76M4y2BD4RNi",
		email: "ereiglar5@chronoengine.com",
		location: "Bandar-e Asaluyeh",
		bio: "Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.",
	},
	{
		username: "cpurvess6",
		firstName: "Collete",
		lastName: "Purvess",
		password: "$2a$10$1/fvAPzR.b7yISuVrQpoXO1kXgchp8zM5aF7POK88B2wOp72UYoNC",
		email: "cpurvess6@nps.gov",
		location: "Mantes-la-Jolie",
		bio: "",
	},
	{
		username: "eolekhov7",
		firstName: "Eileen",
		lastName: "Olekhov",
		password: "$2a$10$UGcByrOd4Ohuz1/6mZpLRg60ONVE9KK1iAbGB6XOx7zt9VSO5E4Wi",
		email: "eolekhov7@lycos.com",
		location: "Hebu",
		bio: "Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.",
	},
	{
		username: "dmordey8",
		firstName: "Dianna",
		lastName: "Mordey",
		password: "$2a$10$.5Z/3bOgAmGhfr7ZKXyFV2gd93rzy9q/1ygnW6fi/4wMYqGAm7pse",
		email: "dmordey8@cocolog-nifty.com",
		location: "Penja",
		bio: "",
	},
	{
		username: "nfrosch9",
		firstName: "Natassia",
		lastName: "Frosch",
		password: "$2a$10$zERo02t6BnnXrURc.Xh.gOY54Gld1gZfr0TATJjy2uO1fdKwpY3Cm",
		email: "nfrosch9@microsoft.com",
		location: "Sicheng",
		bio: "",
	},
];

export default users;
